### ISSUE TITLE
DPL-561 Clean up TODO items

### ISSUE THREAD

**Issue by sdjmchattie** [sanger/lighthouse-ui#434]
**Describe the Housekeeping**
Clean up TODO items spread throughout the code.

**Related issues**
Some of the TODO items are listed under https://github.com/sanger/lighthouse-ui/issues/46 and should probably be addressed at the same time.

**Additional context**
There are a lot of TODO items spread throughout the code base and we should avoid letting them build up or stay this way forever.  The issues are as follows:

- [x] [Add error handling to CSV parsing](https://github.com/sanger/lighthouse-ui/blob/develop/modules/csv.js#L4)
- [x] [Extract label layouts to config](https://github.com/sanger/lighthouse-ui/blob/develop/modules/sprint_general_labels.js#L8) - [also here](https://github.com/sanger/lighthouse-ui/blob/develop/modules/sprint_general_labels.js#L8) -- These layouts should be moved to a JSON config file of some sort and loaded in from there.
- [x] [Pass a function for printing labels](https://github.com/sanger/lighthouse-ui/blob/develop/modules/sprint_general_labels.js#L112) -- Not sure if this is already optimal or not.  It could have a function passed to the destination plate label printing method to handle the printing request, but it feels a bit redundant.  I'm more concerned by the handling of the response.  It looks like the throw/catch/return mechanism is just returning the same object that would have been returned if the response object was returned directly, no matter whether it was success of not.
- [x] [Improve declaration of enumerated status values](https://github.com/sanger/lighthouse-ui/blob/develop/modules/statuses.js#L1) -- This is an enum in disguise.  I think we can probably use the [built-in enum capabilities of JavaScript](https://www.w3schools.com/java/ref_keyword_enum.asp) for this.
- [x] [Create a component for displaying the status](https://github.com/sanger/lighthouse-ui/blob/develop/pages/reports.vue#L19) - [also here](https://github.com/sanger/lighthouse-ui/blob/develop/pages/reports.vue#L85) -- This is addressed in the related issue for this issue as well.  A component similar to AlertDialog would make this a lot cleaner and remove duplication.
- [x] [Use JavaScript language features to process responses](https://github.com/sanger/lighthouse-ui/blob/develop/pages/sentinel_create_samples.vue#L96) -- In particular, these objects can probably be processed with [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) rather than filtering the original objects and then counting successes and errors on the original objects.  It also seems like the `sentinelSampleCreationAlert` needn't be a separate method since it is only ever called by the last line of the method before it.
- [x] [Move constants to a separate module](https://github.com/sanger/lighthouse-ui/blob/develop/test/modules/sprint_general_labels.spec.js#L9) - [also here](https://github.com/sanger/lighthouse-ui/blob/develop/test/modules/sprint_reagent_aliquot_labels.spec.js#L6) -- These constants could go in a separate helper module for SPrint testing, like the way the actual modules have a separate shared constants module.
- [x] [Move integration like tests to an integration suite](https://github.com/sanger/lighthouse-ui/blob/develop/test/pages/sentinel_create_samples.spec.js#L36) - [also here](https://github.com/sanger/lighthouse-ui/blob/develop/test/pages/reports.spec.js#L143-L144) -- These tests are testing the behaviour of the interface rather than the way the data is processed by our functions.  They should probably be moved to an integration suite (not sure if this already exists).
